server:
  port: 8080

app:
  name: @project.name@
  version: @project.version@
  build-time: @timestamp@

spring:
  cache:
    type: simple

github:
  api:
    base-url: https://api.github.com
    token: ${GITHUB_TOKEN:}
